service: game-hub-user-api

frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.cjs' # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      # If you don't have DynamoDB running locally
      noStart: true
    migration:
      dir: 'offline/migrations'
    stages:
      - dev
      - int
      - prod

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - Effect: Allow
          Action:
            - dynamodb:Query
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"

functions:
  api:
    handler: src/index.handler
    environment: ${file(env.${sls:stage, self:provider.stage}.json)}
    timeout: 30
    events:
      - httpApi: "*"

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: entityType
            AttributeType: S
          - AttributeName: id
            AttributeType: S
          - AttributeName: gsiOnePk
            AttributeType: S
        KeySchema:
          - AttributeName: entityType
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsiOneIndex
            KeySchema:
              - AttributeName: gsiOnePk
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
